id: A45C1779C
title: Māṇavikā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:58:05.849366
  last_modified_at: 2022-03-01 22:58:05.849374
